security:
  enable_authenticator_manager: false
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    app_user_provider:
      entity:
        class: App\User\User
        property: email
  firewalls:
    api:
      pattern: ^/api
      security: false
      stateless: true
    admin:
      provider: app_user_provider
      pattern: ^/admin
      security: true
      anonymous: true
      form_login:
        login_path: admin_login
        check_path: admin_login
      logout:
        path: admin_logout
        target: admin_login

  access_control:
    - { path: '/admin/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: '/admin', roles: ROLE_ADMIN }
