version: "3.7"

services:
  app:
    build:
      context: ../..
      dockerfile: ./.docker/local/Dockerfile
      args:
        VERSION: dev
    command:
      - run
  app-debug:
    build:
      context: ../..
      dockerfile: ./.docker/local/Dockerfile
      args:
        VERSION: dev
    command:
      - run

  app-test:
    build:
      context: ../..
      dockerfile: ./.docker/local/Dockerfile
      args:
        VERSION: dev
    command:
      - run

  database:
    volumes:
      - db:/var/lib/mysql
  s3:
    volumes:
      - s3:/data

volumes:
  db:
  s3:
