version: "3.7"

services:
  app: &appconfig
    image: focusly
    expose:
      - 80
    links:
      - database
      - redis
      - "s3:media.s3"
    environment:
      HOST_PROJECT_DIR: ${PWD}
      DB_PORT: "3306"
      DB_DATABASE: "dockerApp"
      DB_USERNAME: "root"
      DB_PASSWORD: "secret"
      MAIL_DRIVER: "smtp"
      MAIL_HOST: "mailhog"
      MAIL_PORT: "1025"
      MAIL_FROM_NAME: "Focusly"
      REDIS_HOST: "redis"
      REDIS_PASSWORD: "null"
      REDIS_PORT: "6379"
      AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
      AWS_PUBLIC_ENDPOINT: "http://s3.lvh.me"
      AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      AWS_DEFAULT_REGION: "eu-west-1"
      AWS_BUCKET: "media"
      AWS_TMP_BUCKET: "tmp"
      AWS_ENDPOINT: "http://s3"
    env_file:
      - '.env'
    healthcheck:
      timeout: 20s
    depends_on: [ database,redis,mailhog ]
  app-debug:
    <<: *appconfig
    env_file:
      - '.env'
      - '.env.debug'
  database:
    image: mysql:5.7.27
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=dockerApp"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 20s
      retries: 10
  redis:
    image: redis:6.2.1
    command: [ "redis-server", "--appendonly", "yes" ]

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379

  mailhog:
    image: "mailhog/mailhog:v1.0.1"

  s3:
    image: minio/minio
    volumes:
      - s3:/data
    environment:
      - "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      - "MINIO_DOMAIN=s3"
    command: server --address :80  --console-address :9000 /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/minio/health/live" ]
      interval: 5s
      timeout: 20s
      retries: 3

  s3-admin:
    image: minio/minio
    environment:
      - "MINIO_ROOT_USER=god"
      - "MINIO_ROOT_PASSWORD=password"
    command: server --address :80  --console-address :9000 /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/minio/health/live" ]
      interval: 5s
      timeout: 20s
      retries: 3


  s3-createbucket:
    image: minio/mc
    depends_on: [ s3 ]
    environment:
      - "MINIO_HOST=s3"
      - "MINIO_BUCKET=media"
      - "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    entrypoint: bash /create-storage.sh
    volumes:
      - ./s3/create-storage.sh:/create-storage.sh
volumes:
  app:
    name: focusly_app
  s3:

networks:
  default:
    name: "focusly"
