version: "3.7"

services:
  app:
    labels:
      traefik.http.routers.focusly-http.rule: Host(`lvh.me`)
      traefik.http.routers.focusly-http.entrypoints: http
      traefik.http.routers.focusly-https.rule: Host(`lvh.me`)
      traefik.http.routers.focusly-https.entrypoints: https
    networks:
      focusly:
  app-debug:
    labels:
      traefik.http.routers.focusly-debug-http.rule: Host(`lvh.me`) && HeadersRegexp(`Cookie`, `XDEBUG_SESSION`)
      traefik.http.routers.focusly-debug-http.entrypoints: http
      traefik.http.routers.focusly-debug-https.rule: Host(`lvh.me`) && HeadersRegexp(`Cookie`, `XDEBUG_SESSION`)
      traefik.http.routers.focusly-debug-https.entrypoints: https
    networks:
      focusly:
  mailhog:
    labels:
      traefik.http.routers.focusly-mailhog-http.rule: Host(`mailhog.lvh.me`)
      traefik.http.routers.focusly-mailhog-http.entrypoints: http
      traefik.http.routers.focusly-mailhog-https.rule: Host(`mailhog.lvh.me`)
      traefik.http.routers.focusly-mailhog-https.entrypoints: https
      traefik.http.services.focusly-mailhog.loadbalancer.server.port: 8025
    networks:
      focusly:

  traefik:
    image: "traefik:v2.4"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
    networks:
      focusly:

  database:
    networks:
      focusly:

  redis:
    networks:
      focusly:

  redis-commander:
    labels:
      traefik.http.routers.focusly-redis-commander-http.rule: Host(`redis.lvh.me`)
      traefik.http.routers.focusly-redis-commander-http.entrypoints: http
      traefik.http.routers.focusly-redis-commander-https.rule: Host(`redis.lvh.me`)
      traefik.http.routers.focusly-redis-commander-https.entrypoints: https
      traefik.http.services.focusly-redis-commander.loadbalancer.server.port: 8081
    networks:
      focusly:

  s3:
    environment:
      - "MINIO_DOMAIN=s3,s3.lvh.me"
    labels:
      traefik.http.routers.focusly-s3-http.rule: Host(`media.s3.lvh.me`)
      traefik.http.routers.focusly-s3-http.entrypoints: http
      traefik.http.routers.focusly-s3-https.rule: Host(`media.s3.lvh.me`)
      traefik.http.routers.focusly-s3-https.entrypoints: https
      traefik.http.services.focusly-s3.loadbalancer.server.port: 80
    networks:
      focusly:

  s3-admin:
    labels:
      traefik.http.routers.focusly-s3-consolehttp.rule: Host(`console.s3.lvh.me`)
      traefik.http.routers.focusly-s3-consolehttp.entrypoints: http
      traefik.http.routers.focusly-s3-consolehttps.rule: Host(`console.s3.lvh.me`)
      traefik.http.routers.focusly-s3-consolehttps.entrypoints: https
      traefik.http.services.focusly-s3-console.loadbalancer.server.port: 9000
    networks:
      focusly:

  s3-createbucket:
    networks:
      focusly:

networks:
  focusly:
    name: "focusly"
